{% set name = "homeharvest" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/homeharvest-{{ version }}.tar.gz
  sha256: c97155ed497ed31751231ec334017ce1687cee2874053ddfeee6d6b2071e7400

build:
  entry_points:
    - homeharvest = homeharvest.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.10,<3.13
    - requests >=2.31.0,<3.0.0
    - pandas >=2.1.1,<3.0.0
    - openpyxl >=3.1.2,<4.0.0

test:
  imports:
    - homeharvest
  commands:
    - pip check
    - homeharvest --help
  requires:
    - pip

about:
  home: https://github.com/Bunsly/HomeHarvest
  summary: Real estate scraping library supporting Zillow, Realtor.com & Redfin.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
