{% set name = "homeharvest" %}
{% set version = "0.4.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/homeharvest-{{ version }}.tar.gz
  sha256: 3cd403fee2d9dfa9e16514f90b3f0069714f5c6d4411f72e09c2518e5c1eb18d

build:
  entry_points:
    - homeharvest = homeharvest.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<3.13
    - requests >=2.31.0,<3.0.0
    - pandas >=2.1.1,<3.0.0
    - pydantic >=2.7.4,<3.0.0
    - tenacity >=9.0.0,<10.0.0

test:
  imports:
    - homeharvest
  commands:
    - pip check
    - homeharvest --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Bunsly/HomeHarvest
  summary: Real estate scraping library supporting Zillow, Realtor.com & Redfin.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
