schema_version: 1

context:
  name: homeharvest
  version: "0.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/homeharvest-${{ version }}.tar.gz
  sha256: b2f4ffa3846a55c21ba1921937f5e236c656e27ef7a1548bf0c7d013aaa00eab

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - homeharvest = homeharvest.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - requests >=2.31.0,<3.0.0
    - pandas >=2.1.1,<3.0.0
    - pydantic >=2.7.4,<3.0.0
    - tenacity >=9.0.0,<10.0.0

tests:
  - python:
      imports:
        - homeharvest
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - homeharvest --help

about:
  summary: Real estate scraping library supporting Zillow, Realtor.com & Redfin.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Bunsly/HomeHarvest

extra:
  recipe-maintainers:
    - thewchan
