schema_version: 1

context:
  name: homeharvest
  version: "0.8.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/homeharvest-${{ version }}.tar.gz
  sha256: 1b8ad3fbd619fe6844c4e7e4093e6b1f245e254b597749b36d3345e0ffa7fe3f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - requests >=2.31.0,<3.0.0
    - pandas >=2.1.1,<3.0.0
    - pydantic >=2.7.4,<3.0.0
    - tenacity >=9.0.0,<10.0.0

tests:
  - python:
      imports:
        - homeharvest
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Real estate scraping library supporting Zillow, Realtor.com & Redfin.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Bunsly/HomeHarvest

extra:
  recipe-maintainers:
    - thewchan
